#!/bin/bash

copied=$(python -c "import sys; sys.stdout.write(u'\u200b'.join(sys.argv[1].decode('utf-8')).encode('utf-8'))" "$@")

if which pbcopy >/dev/null
then
    echo $copied | pbcopy
else
    echo $copied | xclip -i -selection clipboard
fi
  
